# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  variables:
    NODE_ENV: 'production'
    REACT_APP_API_URL: 'https://api.habitualizer.com/graphql'
  parameter-store:
    CDN_S3_BUCKET_NAME: '/habit-web/web_cdn_bucket_name'
    CDN_DISTRIBUTION_ID: '/habit-web/cloudfront_id'
    GITHUB_PACKAGES_TOKEN: '/rk-shared/github/packages/token'

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - curl -Ls https://releases.hashicorp.com/terraform/0.13.0/terraform_0.13.0_linux_amd64.zip -o terraform.zip
      - unzip -qq terraform.zip
      - mv terraform /usr/local/bin/terraform
      - chmod a+x /usr/local/bin/terraform
      - echo "//npm.pkg.github.com/:_authToken=$GITHUB_PACKAGES_TOKEN" > ~/.npmrc

  pre_build:
    commands:
      - yarn install
      - cd "$CODEBUILD_SRC_DIR/infra"
      - terraform init

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - yarn build
      - cd "$CODEBUILD_SRC_DIR/infra"
      - terraform plan -out="$CODEBUILD_SRC_DIR/infra/main.tf.plan"
      - terraform apply -auto-approve "$CODEBUILD_SRC_DIR/infra/main.tf.plan"
      - cd "$CODEBUILD_SRC_DIR"
      - aws s3 cp --recursive "./build/" "s3://$CDN_S3_BUCKET_NAME/"
      - aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --invalidation-batch "Paths={Quantity=1,Items=[/*]},CallerReference=$(date +%s)"
    finally:
      - rm -f "$CODEBUILD_SRC_DIR/infra/main.tf.plan"
